# Generated by Django 2.2.5 on 2019-09-22 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth', '0010_customuser_noti_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
    ]
