# Generated by Django 2.2.5 on 2019-09-24 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth', '0011_auto_20190922_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
