# Generated by Django 2.2.5 on 2019-09-24 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth', '0012_auto_20190924_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default='download.jpg', upload_to=''),
        ),
    ]
