# Generated by Django 2.2.5 on 2019-09-28 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comportal', '0007_auto_20190110_1001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complain',
            name='avail',
        ),
        migrations.RemoveField(
            model_name='complain',
            name='need',
        ),
        migrations.RemoveField(
            model_name='complain',
            name='type',
        ),
    ]
