# Generated by Django 2.2.5 on 2019-09-28 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comportal', '0008_auto_20190928_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='complain',
            name='avail',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='complain',
            name='need',
            field=models.CharField(choices=[('R', 'repair'), ('C', 'change')], default='R', max_length=1),
        ),
        migrations.AddField(
            model_name='complain',
            name='type',
            field=models.CharField(choices=[('I', 'individual'), ('G', 'general')], default='G', max_length=1),
        ),
    ]
