# Generated by Django 2.2.5 on 2019-09-28 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comportal', '0009_auto_20190928_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complain',
            name='area',
        ),
        migrations.AddField(
            model_name='complain',
            name='category',
            field=models.CharField(choices=[('E', 'electrical'), ('P', 'plumber'), ('C', 'carpenter'), ('H', 'housekeeping')], default='H', max_length=1),
        ),
    ]
