# Generated by Django 2.2.5 on 2019-09-28 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comportal', '0011_remove_complain_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complain',
            old_name='details',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='complain',
            name='avail',
        ),
        migrations.RemoveField(
            model_name='complain',
            name='need',
        ),
    ]
