# Generated by Django 2.2.5 on 2019-09-29 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comportal', '0012_auto_20190928_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='complain',
            name='pimage',
            field=models.ImageField(default='download.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='complain',
            name='category',
            field=models.CharField(choices=[('E', 'electrical'), ('P', 'plumber'), ('C', 'carpenter'), ('H', 'housekeeping'), ('D', 'healthcare')], default='H', max_length=1),
        ),
    ]
