# Generated by Django 2.2.5 on 2019-10-01 09:18

import comportal.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comportal', '0013_auto_20190929_1903'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Image')),
                ('complain', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='comportal.Complain')),
            ],
        ),
    ]
