# Generated by Django 2.2.5 on 2019-10-01 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comportal', '0014_images'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Images',
        ),
    ]
