# Generated by Django 2.2.5 on 2019-10-01 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comportal', '0015_delete_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='')),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('complain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='images', to='comportal.Complain')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
