# Generated by Django 2.2.5 on 2019-10-01 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comportal', '0016_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='Images',
        ),
    ]
