# Generated by Django 2.2.5 on 2019-10-01 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comportal', '0017_auto_20191001_1513'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='Image',
        ),
    ]
