# Generated by Django 2.2.5 on 2019-10-01 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comportal', '0018_auto_20191001_1516'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={},
        ),
        migrations.RemoveField(
            model_name='image',
            name='position',
        ),
        migrations.AlterField(
            model_name='image',
            name='complain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='comportal.Complain'),
        ),
    ]
