# Generated by Django 2.2.5 on 2019-10-02 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comportal', '0019_auto_20191001_1524'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
