# Generated by Django 2.2.5 on 2019-10-09 13:18

import comportal.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comportal', '0022_auto_20191005_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=comportal.models.get_image_filename, verbose_name='Image')),
                ('complain', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='comportal.Complain')),
            ],
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
